Coderockr/vitrine-social

docs/Makefile
docs/api.apib
docs/index.html

Doc da api

---

database.sql

Connected to #6 
---
Segue SQL de criação das tabelas da base de dados.

Base de Dados

---

Frontend/public/index.html
Frontend/src/components/Categories.js
Frontend/src/components/CategoriesItem.js
Frontend/src/containers/App/index.js

Add Prototype Categories

---

Makefile
README.md
devops/dbconfig.yml
devops/migrations/20170826155748-default-categories.sql

Migrations

---

devops/migrations/20170826162654-need-unity.sql
devops/migrations/20170826162936-fixtures.sql
docs/api.apib
docs/index.html

Novo campo e fixtures

---

Frontend/src/App.css
Frontend/src/components/Categories/index.js
Frontend/src/components/CategoriesItem/index.js
Frontend/src/components/CategoriesItem/style.css

Add Categories

---

Frontend/src/components/Categories/index.js
Frontend/src/components/CategoriesItem/index.js
Frontend/src/components/CategoriesItem/style.css
Frontend/src/components/Search/index.js

Final Categories

---

codecov.yml
docker-compose.yml
docs/api.apib
docs/index.html
server/cmd/serve.go
server/db/repo/need.go
server/db/repo/organization.go
server/handlers/auth.go
server/handlers/create_need.go
server/handlers/create_need_test.go
server/handlers/json-structs.go
server/handlers/jwt.go
server/handlers/need.go
server/handlers/organization.go
server/model/model.go

Issue #48 - Criação de Necessidade

---

.gitignore
server/cmd/serve.go
server/db/repo/organization.go
server/handlers/organization.go
server/handlers/organization_test.go

Connected to: #44 
----
Pessoal, eu vi que tem um storage implementado, possivelmente para enviar as imagens para o s3, mas não está sendo utilizado ainda né?

DeleteImagemHandler with tests

---

docs/api.apib
docs/index.html
server/cmd/serve.go
server/db/repo/need.go
server/handlers/need.go
server/handlers/need_response.go
server/handlers/need_test.go

Update Need handler

---

devops/migrations/20180524174400-default.sql
docs/api.apib
server/Gopkg.lock
server/Gopkg.toml
server/cmd/create.go
server/db/repo/organization.go
server/handlers/json-structs.go
server/handlers/organization.go
server/handlers/organization_test.go
server/model/model.go

Change address fields

---

server/middlewares/cors.go

Enable CORS Rest

---

docs/api.apib
docs/index.html
server/db/repo/need.go
server/handlers/need.go
server/handlers/need_test.go

Enable update status on endpoint update need

---

devops/migrations/20180611105900-change-icon-slug.sql
docs/api.apib
server/db/repo/search.go
server/handlers/category.go
server/handlers/json-structs.go
server/handlers/need.go
server/handlers/organization.go
server/handlers/search.go
server/model/model.go

Change icon field to slug

---

docs/api.apib
docs/index.html
server/db/repo/search.go
server/handlers/search.go

- Param `text` optional
- Param `order_by `changed to `orderBy`
- Add where to get only ACTIVE needs

Hotfix search without text required and orderBy

---

devops/migrations/20180612101731-change-unity-unit.sql
docs/api.apib
docs/index.html
server/db/repo/need.go
server/db/repo/search.go
server/handlers/auth_test.go
server/handlers/json-structs.go
server/handlers/need.go
server/handlers/need_test.go
server/handlers/organization.go
server/handlers/search.go
server/model/model.go

Connected to #155 
Done:
- Changed unity to unit on database, model and handlers
- Add need created_at and updated_at params
- Add search status params
- Add pagination and imagens on search handler's return
- Updated docs

Fix search handler and need model

---

devops/migrations/20180612161737-fix-need-response.sql
server/cmd/serve.go
server/db/repo/need_response.go
server/handlers/need_response.go
server/model/model.go

Fix need response create

---

server/db/repo/search.go

Fix params number

---

server/db/repo/search.go

Fix status params and search by organization name

---

frontend/src/components/Pagination/Pagination.js
frontend/src/containers/Home/Home.js
frontend/src/containers/Results/Results.js

Implemented Pagination

---

server/handlers/create_need.go
server/handlers/create_need_test.go

Save param unit

---

frontend/src/App.js
frontend/src/components/BottomNotification/BottomNotification.js
frontend/src/components/BottomNotification/styles.module.scss
frontend/src/components/Footer/styles.module.scss
frontend/src/containers/About/About.js
frontend/src/containers/About/styles.module.scss
frontend/src/containers/Contact/Contact.js
frontend/src/containers/Contact/index.js
frontend/src/containers/Contact/styles.module.scss
frontend/src/containers/Login/Login.js
frontend/src/utils/styles/global.module.scss

Implemented contact page and fixed About page

---

frontend/src/App.js
frontend/src/components/ChangePassword/ChangePassword.js
frontend/src/components/ChangePassword/index.js
frontend/src/components/ChangePassword/styles.module.scss
frontend/src/components/Layout/Layout.js
frontend/src/containers/Login/styles.module.scss
frontend/src/containers/ResetPassword/ResetPassword.js
frontend/src/containers/ResetPassword/index.js
frontend/src/containers/ResetPassword/styles.module.scss
frontend/src/containers/Results/Results.js
frontend/src/utils/styles/global.module.scss

Implemented change password compenent and reset password container

---

frontend/src/components/ChangePassword/ChangePassword.js
frontend/src/components/Layout/Layout.js
frontend/src/components/ResponseFeedback/ResponseFeedback.js
frontend/src/components/ResponseFeedback/styles.module.scss
frontend/src/containers/OrganizationProfile/OrganizationProfile.js
frontend/src/containers/OrganizationProfile/styles.module.scss
frontend/src/utils/styles/global.module.scss

Implemented update password

---

frontend/src/components/Header/Header.js
frontend/src/components/Header/styles.module.scss
frontend/src/containers/Login/Login.js
frontend/src/containers/Login/styles.module.scss
frontend/src/utils/api.js
frontend/src/utils/styles/common.scss
frontend/src/utils/styles/global.module.scss

Implemented user menu and log out

---

.travis.yml
devops/deploy.sh

Hotfix travis migrations

---

server/db/repo/need.go
server/handlers/need.go

Fix need update_at param

---

.travis.yml

After deploy command to invalid cloudfront cache

---

Makefile
devops/dbconfig.yml

algumas melhorias no Makefile para corrigir o `make migrations`

Migrations on dev

---

frontend/src/App.js
frontend/src/components/CategoriesItem/styles.module.scss
frontend/src/containers/ForgotPassword/ForgotPassword.js
frontend/src/containers/ForgotPassword/index.js
frontend/src/containers/ForgotPassword/styles.module.scss

Implemented Forgot Password

---

frontend/package.json
frontend/src/App.js
frontend/src/components/ChangePassword/ChangePassword.js
frontend/src/components/ContactForm/ContactForm.js
frontend/src/components/OrganizationProfileForm/OrganizationProfileForm.js
frontend/src/components/RequestDetails/RequestDetails.js
frontend/src/components/RequestForm/RequestForm.js
frontend/src/components/Requests/Requests.js
frontend/src/containers/Contact/Contact.js
frontend/src/containers/ForgotPassword/ForgotPassword.js
frontend/yarn.lock

Implemented Google Analytics with react-ga

---

server/db/repo/need.go
server/db/repo/organization.go

Não estava retornando a organization de uma need na busca. Então não pegava o email correto para enviar.

Fix send email need response

---

frontend/src/components/CategoriesItem/styles.module.scss
frontend/src/components/ErrorCard/styles.module.scss
frontend/src/components/Footer/Footer.js
frontend/src/components/Footer/styles.module.scss
frontend/src/components/Header/styles.module.scss
frontend/src/components/ItemIndicator/ItemIndicator.js
frontend/src/components/ItemIndicator/styles.module.scss
frontend/src/components/RequestDetails/styles.module.scss
frontend/src/components/Requests/Requests.js
frontend/src/components/Requests/styles.module.scss
frontend/src/components/Search/Search.js
frontend/src/components/Search/styles.module.scss
frontend/src/containers/OrganizationProfile/styles.module.scss

Adjustments for smaller phones

---

server/db/repo/organization.go
server/handlers/organization.go
server/handlers/organization_test.go
server/model/model.go
server/storage/imageStorage.go
server/storage/imageStorage_test.go

Set logo_image_id NULL when removing logo

---

server/db/repo/search.go

Fix search with lower

---

server/handlers/organization.go

Remove old logo

---

frontend/src/components/OrganizationProfileForm/OrganizationProfileForm.js

Removed required rule from complement

---

frontend/src/components/RequestFormCreate/RequestFormCreate.js
frontend/src/components/Requests/styles.module.scss
frontend/src/containers/OrganizationProfile/OrganizationProfile.js
frontend/src/containers/OrganizationProfile/styles.module.scss

Fixed save loop, about paragraphs, actionWrapper and website wrap

---

frontend/src/components/Header/Header.js
frontend/src/containers/Login/Login.js

pt paths quick fix

---

frontend/.env.local
frontend/src/components/RequestDetails/RequestDetails.js

Changed share URL and configured docker locally

---

frontend/package.json
frontend/src/App.js
frontend/yarn.lock

Added HotJar

---

.travis.yml

Add StrictHostKeyChecking no to .ssh

---

frontend/public/index.html

Install jivochat script

---

server/cmd/serve.go
server/handlers/contact.go
server/handlers/newsletter.go
server/newsletter/newsletter.go

Newslatter handler and save on contact

---

frontend/src/components/Categories/Categories.js
frontend/src/components/CategoriesItem/CategoriesItem.js
frontend/src/components/CategoriesItem/styles.module.scss

connected to #201 
Mudei o componente que renderiza as categorias na home. Agora caso não tenha nenhuma solicitação em uma determinada categoria, ela deve aparecer desabilitada.
_PS: Deixei os prints de como ficou esse componente na issue, mas posso mover para cá se necessário._

feature(category): Disable link without needs

---

frontend/src/utils/auth.js
frontend/yarn.lock

Update apiImage on login

---

frontend/src/components/Footer/Footer.js
frontend/src/components/RequestCard/styles.module.scss
frontend/src/containers/NotFound/styles.module.scss
frontend/src/containers/OrganizationProfile/OrganizationProfile.js

Eu corrigi o que estava quebrando os estilos em todas as telas.

Fixed styles by moving h1, h2, h3 in not found inside a class

---

frontend/src/components/Footer/Footer.js

Fixed footer copyright

---

README.md

While I was trying to setup the project in my desktop I discovered this little issue on the README. I had a lot of trouble going through those steps on README and I couldn't run the app here, but at least I could fix this one.

README fix on docker setup
